# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_type',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
