# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_service_type_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_type',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
