# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160507_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='interested_action',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Buy', 'Buy')], default='Rent', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='interested_property',
            field=models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential')], default='Rent', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='other_service',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('Mortgage', 'Mortgage')], default='', max_length=50),
        ),
    ]
