# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160508_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='other_service',
            field=models.CharField(choices=[('Insurance', 'Insurance'), ('Mortgage', 'Mortgage')], default='Insurance', max_length=50),
        ),
    ]
