# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20160508_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='other_service',
            new_name='interested_service',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contactable',
        ),
        migrations.AddField(
            model_name='client',
            name='email_contactable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_contactable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='receive_news',
            field=models.BooleanField(default=True),
        ),
    ]
