# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20160517_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='interested_action',
        ),
        migrations.RemoveField(
            model_name='client',
            name='interested_property',
        ),
        migrations.RemoveField(
            model_name='client',
            name='interested_service',
        ),
        migrations.AddField(
            model_name='client',
            name='interested_action',
            field=models.ManyToManyField(related_name='action', to='client.Action_Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='interested_property',
            field=models.ManyToManyField(related_name='property', to='client.Property_Type'),
        ),
        migrations.AddField(
            model_name='client',
            name='interested_service',
            field=models.ManyToManyField(related_name='service', to='client.Service_Type'),
        ),
    ]
