# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential',
            name='BEDROOMS',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='residential',
            name='LET_FURN_ID',
            field=models.IntegerField(choices=[(b'0', b'Furnished'), (b'1', b'Part Furnished'), (b'2', b'Unfurnished'), (b'3', b'Not Specified'), (b'4', b'Furnished/ Un Furnishedf')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='LET_RENT_FREQUENCY',
            field=models.IntegerField(choices=[(b'0', b'Weekly'), (b'1', b'Monthly'), (b'2', b'Quarterly'), (b'3', b'Annual'), (b'5', b'Per person per week(Students Lettings only)')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='PRICE',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='residential',
            name='PRICE_QUALIFIER',
            field=models.IntegerField(choices=[(b'0', b'Default'), (b'1', b'POA'), (b'2', b'Guide Price'), (b'3', b'Fixed Price'), (b'4', b'Offers in Excess'), (b'5', b'OIRO'), (b'6', b'Sales by Tender'), (b'7', b'From(new homes and commercial only)'), (b'9', b'Shared Ownership'), (b'10', b'Offers Over'), (b'11', b'Part Buy Part Rent'), (b'12', b'Shared Equity'), (b'14', b'Equity Loan'), (b'15', b'Offers Invited')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='PUBLISHED_FLAG',
            field=models.IntegerField(choices=[(b'0', b'Hidden/invisible'), (b'1', b'Visible')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='TRANS_TYPE_ID',
            field=models.IntegerField(choices=[(b'1', b'Resale'), (b'2', b'Lettings')]),
        ),
    ]
