# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-09 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential',
            name='LET_FURN_ID',
            field=models.IntegerField(blank=True, choices=[(0, b'Furnished'), (1, b'Part Furnished'), (2, b'Unfurnished'), (3, b'Not Specified'), (4, b'Furnished/ Un Furnished')], null=True),
        ),
        migrations.AlterField(
            model_name='save_search',
            name='cr_furnished',
            field=models.IntegerField(blank=True, choices=[(0, b'Furnished'), (1, b'Part Furnished'), (2, b'Unfurnished'), (3, b'Not Specified'), (4, b'Furnished/ Un Furnished')], null=True),
        ),
        migrations.AlterField(
            model_name='save_search',
            name='r_furnished',
            field=models.IntegerField(blank=True, choices=[(0, b'Furnished'), (1, b'Part Furnished'), (2, b'Unfurnished'), (3, b'Not Specified'), (4, b'Furnished/ Un Furnished')], null=True),
        ),
    ]
