# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential',
            name='DESCRIPTION',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='residential',
            name='SUMMARY',
            field=models.TextField(),
        ),
    ]
