# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0002_auto_20160408_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential',
            name='ADDRESS_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='residential',
            name='ADDRESS_3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='residential',
            name='ADDRESS_4',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='residential',
            name='CREATE_DATE',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='residential',
            name='DESCRIPTION',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='residential',
            name='LET_FURN_ID',
            field=models.IntegerField(choices=[(0, b'Furnished'), (1, b'Part Furnished'), (2, b'Unfurnished'), (3, b'Not Specified'), (4, b'Furnished/ Un Furnishedf')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='LET_RENT_FREQUENCY',
            field=models.IntegerField(choices=[(0, b'Weekly'), (1, b'Monthly'), (2, b'Quarterly'), (3, b'Annual'), (5, b'Per person per week(Students Lettings only)')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_00',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_50',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_51',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_52',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_53',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_TEXT_00',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_TEXT_01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_TEXT_50',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_TEXT_51',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_TEXT_52',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_DOCUMENT_TEXT_53',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_FLOOR_PLAN_00',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_FLOOR_PLAN_01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_FLOOR_PLAN_TEXT_00',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_FLOOR_PLAN_TEXT_01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_00',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_02',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_03',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_04',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_05',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_06',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_07',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_08',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_09',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_13',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_14',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_15',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_16',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_17',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_18',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_19',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_60',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_61',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_TEXT_60',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_TEXT_61',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_VIRTUAL_TOUR_01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_VIRTUAL_TOUR_02',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_VIRTUAL_TOUR_TEXT_01',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_VIRTUAL_TOUR_TEXT_02',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='residential',
            name='PRICE_QUALIFIER',
            field=models.IntegerField(choices=[(0, b'Default'), (1, b'POA'), (2, b'Guide Price'), (3, b'Fixed Price'), (4, b'Offers in Excess'), (5, b'OIRO'), (6, b'Sales by Tender'), (7, b'From(new homes and commercial only)'), (9, b'Shared Ownership'), (10, b'Offers Over'), (11, b'Part Buy Part Rent'), (12, b'Shared Equity'), (14, b'Equity Loan'), (15, b'Offers Invited')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='PUBLISHED_FLAG',
            field=models.IntegerField(choices=[(0, b'Hidden/invisible'), (1, b'Visible')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='STATUS_ID',
            field=models.IntegerField(choices=[(0, b'Available'), (1, b'SSTC(Sales only)'), (2, b'SSTCM(Scottish Sales only'), (3, b'Under offer(Sales only'), (4, b'Reserved(Sales only'), (5, b'Let Agreed(Lettings only')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='TRANS_TYPE_ID',
            field=models.IntegerField(choices=[(1, b'Resale'), (2, b'Lettings')]),
        ),
        migrations.AlterField(
            model_name='residential',
            name='UPDATE_DATE',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
