# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('westgate_estates', '0003_auto_20160408_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residential_Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='westgate_estates.Residential')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
