# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0003_auto_20160705_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residential',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='save_search',
            options={'verbose_name': 'Saved Search', 'verbose_name_plural': 'Saved Searches'},
        ),
        migrations.AlterField(
            model_name='residential',
            name='STATUS_ID',
            field=models.IntegerField(blank=True, choices=[(0, b'Available'), (1, b'SSTC(Sales only)'), (2, b'SSTCM(Scottish Sales only)'), (3, b'Under offer(Sales only)'), (4, b'Reserved(Sales only)'), (5, b'Let Agreed(Lettings only)')], null=True),
        ),
    ]
