# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 22:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0004_residential_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential_favorite',
            name='user',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
