# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0004_auto_20160706_0551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_enquiry',
            options={'verbose_name': 'Service Enquiry', 'verbose_name_plural': 'Service Enquiries'},
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_00',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_01',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_02',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_03',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_04',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_05',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_06',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_07',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_08',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
