# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0005_auto_20160706_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_09',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_10',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_11',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_12',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_13',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_14',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_15',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_16',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_17',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_18',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_19',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_60',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_61',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='residential',
            name='MEDIA_IMAGE_TEXT_61',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
