# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('westgate_estates', '0005_auto_20160508_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_low_price', models.FloatField()),
                ('r_high_price', models.FloatField()),
                ('r_low_bedroom', models.IntegerField()),
                ('r_high_bedroom', models.IntegerField()),
                ('r_furnished', models.IntegerField()),
                ('s_low_price', models.FloatField()),
                ('s_high_price', models.FloatField()),
                ('s_low_bedroom', models.IntegerField()),
                ('s_high_bedroom', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
