# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0010_auto_20160512_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_search',
            name='receive_email',
            field=models.BooleanField(default=False),
        ),
    ]
