# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0011_save_search_receive_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commercial',
        ),
        migrations.AddField(
            model_name='residential',
            name='RESCOM',
            field=models.IntegerField(default=0),
        ),
    ]
