# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-13 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('westgate_estates', '0012_auto_20160613_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential',
            name='RESCOM',
            field=models.IntegerField(choices=[(0, b'Residential'), (1, b'Commercial')], default=0),
        ),
    ]
